### ISSUE TITLE
Problem on linux with TelloMissionFile.js

### ISSUE THREAD

**Issue by neurici** [jsolderitsch/tello-nodejs#1]
neuro@peppermint-usb ~/drona/tello-nodejs-master-x86 $ node TelloMissionFile.js 
/home/neuro/drona/tello-nodejs-master-x86/TelloMissionFile.js:47
    let rx;
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by neurici** [comment]
on windows, work's like a charm!

**Comment by jor3l** [comment]
problem is your node version
